title: Capital Code - Transforming Software Engineering
email: info@capcode.io
description: >-
  Capital Code is a company created by software engineering professionals
  that invests in and builds capital software -- development tools,
  frameworks and methodologies.

url: "https://capcode.io"
github_username: capital-code

markdown: kramdown

theme: jekyll-theme-hacker

google_analytics: "UA-174548013-1"

exclude:
  - Gemfile
  - Gemfile.lock

